### ISSUE TITLE
Magento Backend Order print give error :POS ID is empty

### ISSUE THREAD

**Issue by pareshpansuriya** [ORBA/magento2_payupl#8]
Magento backend Order print give error:

a:4:{i:0;s:16:"POS ID is empty.";i:1;s:8042:"#0 /var/www/html/xxxxx/app/code/Orba/Payupl/Model/Client.php(35): Orba\Payupl\Model\Client\Classic\Config->setConfig()
#1 /var/www/html/xxxxx/app/code/Orba/Payupl/Model/Client/Classic.php(23): Orba\Payupl\Model\Client->__construct(Object(Orba\Payupl\Model\Client\Classic\Config), Object(Orba\Payupl\Model\Client\Classic\Order), Object(Orba\Payupl\Model\Client\Classic\Refund))
#2 /var/www/html/xxxxx/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(93): Orba\Payupl\Model\Client\Classic->__construct(Object(Orba\Payupl\Model\Client\Classic\Config), Object(Orba\Payupl\Model\Client\Classic\Order), Object(Orba\Payupl\Model\Client\Classic\Refund))
#3 /var/www/html/xxxxx/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(89): Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject('Orba\\Payupl\\Mod...', Array)
#4 /var/www/html/xxxxx/vendor/magento/framework/ObjectManager/ObjectManager.php(57): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Orba\\Payupl\\Mod...', Array)
#5 /var/www/html/xxxxx/app/code/Orba/Payupl/Model/ClientFactory.php(42): Magento\Framework\ObjectManager\ObjectManager->create('Orba\\Payupl\\Mod...', Array)
...............

May be because payupl payment method is set in other store and we are print order of that store  and payupl payment method is not enabled in default store(admin store)

**Comment by michalbiarda** [comment]
Hi @pareshpansuriya 

Could you please provide steps to reproduce the error?
